# Dockerfile.backend

FROM python:3.11-slim

# Create and set working directory
WORKDIR /code

# Copy everything into container
COPY ./app /code/app
COPY requirements.txt /code

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose FastAPI port
EXPOSE 8000

# Run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

